### ISSUE TITLE
Couldn't find package "react-native-app-intro-slider" on the "npm" registry.

### ISSUE THREAD

**Issue by pramjeet** [Jacse/react-native-app-intro-slider#1]
Hi @Jacse, first of all, thanks for the package! But it appears it hasn't been available in npm yet.

**Comment by Jacse** [comment]
[It's on npm now! 🎆 ](https://www.npmjs.com/package/react-native-app-intro-slider)

**Comment by pramjeet** [comment]
Thanks!
