### ISSUE TITLE
Navigation from the skip button

### ISSUE THREAD

**Issue by fithaN** [Jacse/react-native-app-intro-slider#10]
How can i navigate to real app after skip or done?

**Comment by EriveltonElias** [comment]
Hi @fithaN 

try use   

onSkip
or onDone 

Example: 

onSkip = { () => // call your action }

**Comment by Jacse** [comment]
As @EriveltonElias metions you can use the `onDone` and `onSkip` props for that.

E.g. if using react-navigation:

```js
class MyComponent extends React.Component {

  _navigateSomewhere = () => {
    this.props.navigation.navigate('someOtherScreen');
  }

  render () {
    return (
      <AppIntroSlider onDone={this._navigateSomewhere} onSkip={this._navigateSomewhere} />
    );
  }
}
```

**Comment by EriveltonElias** [comment]
@Jacse can you close this issue?
