### ISSUE TITLE
showNextButton, showDoneButton appear when set to false

### ISSUE THREAD

**Issue by safaiyeh** [Jacse/react-native-app-intro-slider#104]
``` javascript
<AppIntroSlider
  showDoneButton={false}
  showNextButton={false} 
  renderItem={this._renderSlide}
  slides={slides}
/>
```

<img width="342" alt="Screen Shot 2019-03-18 at 6 46 19 PM" src="https://user-images.githubusercontent.com/8675043/54574586-21b29680-49ae-11e9-86bf-6ce816679d3b.png">

**Comment by safaiyeh** [comment]
https://github.com/Jacse/react-native-app-intro-slider/pull/105

**Comment by safaiyeh** [comment]
^ My attempt to a solution

**Comment by Jacse** [comment]
I think this is due to a Github-NPM version mismatch. Does the issue persist if you uninstall the component and install using `npm i git+https://github.com/Jacse/react-native-app-intro-slider.git`?

**Comment by Jacse** [comment]
Should be fixed with the newest version on npm.

**Comment by feliciah6** [comment]
I am trying to add a button similar to the one up there "sign in with google" Can you help me or show me here how u added it?
