### ISSUE TITLE
renderItem "safe-space" props are null since version 1.1.2

### ISSUE THREAD

**Issue by filippoitaliano** [Jacse/react-native-app-intro-slider#109]
Since version 1.1.2 was released, the properties `topSpacer` and `bottomSpacer` are null (not present at all) in the `renderItem` param. The prop description isn't changed in the [README](https://github.com/Jacse/react-native-app-intro-slider/blob/master/README.md), but I can see that the props are not used anymore in the DefaultSlide style, looking [here in the changelog](https://github.com/Jacse/react-native-app-intro-slider/commit/1c3d6bbced0ce089f2bdfc4533be5e3f9a375929#diff-27e95a3b81ed6320d6163c66625c41cdL15).

What's the expected behaviour?

**Comment by Jacse** [comment]
It’s a mistake that they’re still in the README, I’ll update that ASAP. Their usage was removed because they seemed to confuse more than help. In most cases, slides should render fine with default settings - if not, users can easily add their own padding. I hope that makes sense.

**Comment by Jacse** [comment]
Should be fixed now
