### ISSUE TITLE
Delay indicator transition

### ISSUE THREAD

**Issue by Cererec** [Jacse/react-native-app-intro-slider#118]
Hi, Is there anyway I could  adjust the  delay of  indicator  transition when swiping?

I want the transition of indicator like this 
![ezgif com-resize](https://user-images.githubusercontent.com/48293712/58385425-d27a8900-8022-11e9-93e3-dcdc77b705ab.gif)

As can be seen, the indicator changes when the previous/next slider almost touches edge of the screen

And is there a way that I can disable the swipe gesture and only use button for prev & next instead?

**Comment by Jacse** [comment]
For you first question, I'm afraid that's not currently supported.

For your second question I would try ``scrollEnabled=false``
