### ISSUE TITLE
renderDoneBottom not working!

### ISSUE THREAD

**Issue by longnk-1447** [Jacse/react-native-app-intro-slider#125]
Hi team support,
I want change style background DoneButton, but it's not working.

```js
...
renderDoneBottom={() => {
<View style={{backgroundColor: '#ccc', flex:  1'}}>
    <Text style={{color: 'white'}}>OK</Text>
</View>
}}
```

Please help me !!! Thanks team support!

**Comment by Jacse** [comment]
Try adding a pound sign in front, e.g. #ccc instead

**Comment by longnk-1447** [comment]
> Try adding a pound sign in front, e.g. #ccc instead

yes i try your solution, but not working

**Comment by Jacse** [comment]
You have a typo. It should be `renderDoneButton` in stead of `renderDoneBottom
