### ISSUE TITLE
Feature request: add prop swipeEnabled

### ISSUE THREAD

**Issue by rsml** [Jacse/react-native-app-intro-slider#126]
**Feature Request:**
Add prop `swipeEnabled` of type `PropTypes.bool`, with default `true`.

The reason for this is I have an interactive piano keyboard inside one of my slides. I want to disable the swiping if and only if the user is currently interacting with the piano keyboard.

Thanks for this project!

**Comment by Jacse** [comment]
As stated in the documentation, the component extends Flatlist, so you can simply supply the `scrollEnabled`-prop 🚀
