### ISSUE TITLE
How to go to x number of index with first render?

### ISSUE THREAD

**Issue by creativemind1** [Jacse/react-native-app-intro-slider#129]
Hello,

How do I go to let's say 40th number of index if I have 50 set of items when slider loads?

**Comment by Jacse** [comment]
Did you try `goToSlide(x)`?

**Comment by ribeirogabriel** [comment]
@Jacse 
How can I apply goToSlide to jump to a specific slide?

**Comment by Jacse** [comment]
It's a method on the component. #108 should give you a pointer on how to use them using ref. If not, let me know.

**Comment by ribeirogabriel** [comment]
@Jacse Thanks! Used ref as you said and was able to accomplish this.
@creativemind1 Just use a ref like this:
         
`this._slider.goToSlide(answers.length);`
`<AppIntroSlider
                     ref={(ref) => this._slider = ref}
                  />`

**Comment by Jacse** [comment]
Closing this since it seems to be resolved.

**Comment by pedrohw12** [comment]
I have the IntroSlider in a drawer page. When I go to another page and come back, the slider is in the same position as I left before, not returning to the first slide. I already tried all the ref things, but doesn't work.

**Comment by ribeirogabriel** [comment]
> I have the IntroSlider in a drawer page. When I go to another page and come back, the slider is in the same position as I left before, not returning to the first slide. I already tried all the ref things, but doesn't work.

Did you tried to reference the Slider and use the method goToSlide?

**Comment by shamtroon** [comment]
I use `this._slider.goToSlide(1);` but it gives me following error

Error : Cannot read property 'goToSlide' of undefined

**Comment by shachardevops** [comment]
> I use `this._slider.goToSlide(1);` but it gives me following error
> 
> Error : Cannot read property 'goToSlide' of undefined

+1
```
  const slider = useRef();





      <AppIntroSlider
        renderItem={renderItem}
        data={slides}
        ref={slider}
        showNextButton={false}
        showDoneButton={false}>
        {console.log(slider)}
      </AppIntroSlider>

**Comment by Jacse** [comment]
Please see [this](https://github.com/Jacse/react-native-app-intro-slider/issues/163#issuecomment-607240292) comment
