### ISSUE TITLE
The slider takes time to load

### ISSUE THREAD

**Issue by chetan-plrch** [Jacse/react-native-app-intro-slider#130]
The slider takes longer time to load if few images (totally ~2MB) are added and even when InteractionManager.runAfterInteractions is been used.

**Comment by Jacse** [comment]
This will be hard to improve since we're relying on React Native's FlatList and native Image components. I'm afraid I don't really know where to go from this issue. Have you tried optimizing your images?

**Comment by Jacse** [comment]
I'm going to close this since it seems inactionable. If anybody comes up with a way to optimize the component, please submit a PR or let me know on this issue.
