### ISSUE TITLE
how to use images in full background? 

### ISSUE THREAD

**Issue by rodionovich221** [Jacse/react-native-app-intro-slider#135]
how to set image in the background as a full image?
I tried to use renderItem method for that, but it's showing a blank screen.

------- Code ----------

```
import intro1 from '../../assets/images/intro1.png';
import intro2 from '../../assets/images/intro2.png';
import intro3 from '../../assets/images/intro3.png';
import intro4 from '../../assets/images/intro4.png';
import intro5 from '../../assets/images/intro5.png';
import logo from '../../assets/images/logo.png';


const styles = StyleSheet.create({
  mainContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  image: {
    width: 320,
    height: 320,
  },
  text: {
    color: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: 'transparent',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 22,
    color: 'white',
    backgroundColor: 'transparent',
    textAlign: 'center',
    marginBottom: 16,
  },
});

const slides = [
  {
    key: 'somethun',
    title: 'Quick setup, good defaults',
    text:
      'React-native-app-intro-slider is easy to setup with a small footprint and no dependencies. And it comes with good default layouts!',
    icon: logo,
    backgroundImage: intro1,
  },
  {
    key: 'somethun1',
    title: 'Super customizable',
    text:
      'The component is also super customizable, so you can adapt it to cover your needs and wants.',
    icon: logo,
    backgroundImage: intro2,
  },
  {
    key: 'somethun2',
    title: 'No need to buy me beer',
    text: 'Usage is all free',
    icon: logo,
    backgroundImage: intro3,
  },
];

export default class App extends React.Component {
  _renderItem = props => (
    <ImageBackground
      style={[
        styles.mainContent,
        {
          width:'100%',
          height: '100%',
        },
      ]}
     source={props.backgroundImage}
    >
      <Image
        source={props.icon}
        style={styles.image}
      />
      <View>
        <Text style={styles.title}>{props.title}</Text>
        <Text style={styles.text}>{props.text}</Text>
      </View>
    </ImageBackground>
  );

  render() {
    return (
       <AppIntroSlider
           slides={slides}
           renderItem={this._renderItem}
          bottomButton />
     );
  }
}
```

Hmm... Render function is not empty, is not showing properly.
Just updating the code of render function. 

![Screen Shot 2019-07-31 at 8 50 36 AM](https://user-images.githubusercontent.com/52396717/62227225-5da03400-b370-11e9-8029-d5caa2fa234b.png)

**Comment by Jacse** [comment]
Hi @rodionovich221,

It seems something is misformed in your code. Could you try to format it properly (e.g. with proper indentation)? I think there are pieces missing, should the render-function be empty?

**Comment by Jacse** [comment]
Also, what version of the library are you using?

**Comment by paynegreen** [comment]
```javascript
_renderItem = ({ props }) => (
    <ImageBackground
      source={props.backgroundImage}
      style={[
        styles.mainContent,
        {
          width: "100%",
          height: "100%"
        }
      ]}>
      {props.title}
      {props.text}
    </ImageBackground>
  );
```
@rodionovich221 Make sure to unpack the props being passed to the `_renderItem` function. v3 made an upgrade and doesn't traverse the json payload to access the select `item` key anymore.

**Comment by Jacse** [comment]
Please also note that there is (no such thing)[https://facebook.github.io/react-native/docs/height-and-width.html] as `100%` height and width in react native. You should use the dimensions supplies to `renderItem` instead. Modifying @paynegreen's answer a little:
```js
_renderItem = ({ props, dimensions }) => (
    <ImageBackground
      source={props.backgroundImage}
      style={[
        styles.mainContent,
        ...dimensions
      ]}>
      {props.title}
      {props.text}
    </ImageBackground>
  );
```

**Comment by rodionovich221** [comment]
> Hi @rodionovich221,
> 
> It seems something is misformed in your code. Could you try to format it properly (e.g. with proper indentation)? I think there are pieces missing, should the render-function be empty?

Strange, the code is not showing on the first one.

render() {
return (
        <AppIntroSlider
          slides={slides}
          onDone={this.on_Done_all_slides}
          showSkipButton={true}
          onSkip={this.on_Skip_slides}
          renderItem={this._renderItem}
        />
      );
}
}

**Comment by rodionovich221** [comment]
> Also, what version of the library are you using?

This is my Package.json file structure.

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-size-matters": "^0.2.1",
    "react-native-spinkit": "^1.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1",
    "react-navigation-animated-switch": "^0.2.1",
    "react-navigation-transitions": "^1.0.12",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
```

**Comment by rodionovich221** [comment]
> ```js
> _renderItem = ({ props }) => (
>     <ImageBackground
>       source={props.backgroundImage}
>       style={[
>         styles.mainContent,
>         {
>           width: "100%",
>           height: "100%"
>         }
>       ]}>
>       {props.title}
>       {props.text}
>     </ImageBackground>
>   );
> ```
> 
> @rodionovich221 Make sure to unpack the props being passed to the `_renderItem` function. v3 made an upgrade and doesn't traverse the json payload to access the select `item` key anymore.

Could you please share more details?

**Comment by paynegreen** [comment]
The earlier version for the `_renderItem` function had an implementation that unpacks the props passed to the function as such `{...item.item}`. In v3 release, this is a breaking change with no unpacking of the `item` before consumption.

**Comment by rodionovich221** [comment]
> The earlier version for the `_renderItem` function had an implementation that unpacks the props passed to the function as such `{...item.item}`. In v3 release, this is a breaking change with no unpacking of the `item` before consumption. Hope this helps.

I am so sorry.. I still did not get the point.
could you please elaborate on how I could update the code based on below code?

```
export default class App extends React.Component {
  _renderItem = props => (
    <ImageBackground
      style={[
        styles.mainContent,
        {
          width:'100%',
          height: '100%',
        },
      ]}
     source={props.backgroundImage}
    >
      <Image
        source={props.icon}
        style={styles.image}
      />
      <View>
        <Text style={styles.title}>{props.title}</Text>
        <Text style={styles.text}>{props.text}</Text>
      </View>
    </ImageBackground>
  );

  render() {
    return (
       <AppIntroSlider
           slides={slides}
           renderItem={this._renderItem}
          bottomButton />
     );
  }
}
```

**Comment by paynegreen** [comment]
Please try this.
```javascript
export default class App extends React.Component {
  _renderItem = ({ props, dimensions }) => (
    <ImageBackground
      style={[
        styles.mainContent,
        ...dimensions
      ]}
     source={props.backgroundImage}
    >
      <Image
        source={props.icon}
        style={styles.image}
      />
      <View>
        <Text style={styles.title}>{props.title}</Text>
        <Text style={styles.text}>{props.text}</Text>
      </View>
    </ImageBackground>
  );

  render() {
    return (
       <AppIntroSlider
           slides={slides}
           renderItem={this._renderItem}
          bottomButton />
     );
  }
}
```

**Comment by rodionovich221** [comment]
> Please try this.
> 
> ```js
> export default class App extends React.Component {
>   _renderItem = ({ props, dimensions }) => (
>     <ImageBackground
>       style={[
>         styles.mainContent,
>         ...dimensions
>       ]}
>      source={props.backgroundImage}
>     >
>       <Image
>         source={props.icon}
>         style={styles.image}
>       />
>       <View>
>         <Text style={styles.title}>{props.title}</Text>
>         <Text style={styles.text}>{props.text}</Text>
>       </View>
>     </ImageBackground>
>   );
> 
>   render() {
>     return (
>        <AppIntroSlider
>            slides={slides}
>            renderItem={this._renderItem}
>           bottomButton />
>      );
>   }
> }
> ```

Thanks for the update.
I tried this one, but it throws me an issue.
TypeError: undefined is not an object
(evaluating 'props.backgroundImage')

**Comment by Jacse** [comment]
`props` should be renamed to `item`

**Comment by rodionovich221** [comment]
> `props` should be renamed to `item`

Thanks for the reply.
I tried with item, but the same thing happened.

**Comment by Jacse** [comment]
What happens if you `console.log(item)`?

**Comment by rodionovich221** [comment]
> What happens if you `console.log(item)`?

I tried item instead of props.
I got this issue.

![Simulator Screen Shot - iPhone X - 2019-08-01 at 00 33 55](https://user-images.githubusercontent.com/52396717/62274132-1bb8d180-b3f4-11e9-974c-e6b78066a9ad.png)

**Comment by Jacse** [comment]
Could you post the complete code of `renderItem`?

**Comment by rodionovich221** [comment]
> Could you post the complete code of `renderItem`?

```
import Icon from 'react-native-vector-icons/FontAwesome';
import AppIntroSlider from 'react-native-app-intro-slider';
import styles from './styles';
import intro1 from '../../../assets/images/intro1.png';
import intro2 from '../../../assets/images/intro2.png';
import intro3 from '../../../assets/images/intro3.png';
import intro4 from '../../../assets/images/intro4.png';
import intro5 from '../../../assets/images/intro5.png';
import logo from '../../../assets/images/logo.png';
import loginBackground from '../../../assets/images/login_background.png';

export default class IntroPage extends Component {
  constructor(props) {
    super(props);
    this.state = {
      show_Main_App: false,
    };
  }

   _renderItem = ({ item, dimensions }) => (
    <ImageBackground
      source={item.backgroundImage}
      style={[
        styles.mainContent,
        ...dimensions
      ]}>
      {item.title}
      {item.text}
    </ImageBackground>
  );

  render() {
    if (this.state.show_Main_App) {
      return (
        //Show something here.
        );
    } else {
      return (
        <AppIntroSlider
          slides={slides}
          showSkipButton={true}
          onSkip={this.on_Skip_slides}
          renderItem={this._renderItem}
        />
      );
    }
  }
}

const slides = [
  {
    key: 'k1',
    title: 'Event Organizer',
    text: 'Best Event Organizers',
    image: logo,
    titleStyle: styles.title,
    textStyle: styles.text,
    imageStyle: styles.image,
    backgroundColor: '#FF1744',
    backgroundImage: intro1,
  },
  {
    key: 'k2',
    title: 'Weather Reports',
    text: 'Latest Weather Reports',
    image: logo,
    titleStyle: styles.title,
    textStyle: styles.text,
    imageStyle: styles.image,
    backgroundColor: '#D500F9',
    backgroundImage: intro2,
  },
  {
    key: 'k3',
    title: 'Technology Informations',
    text: 'Latest Technology Reports',
    image: logo,
    titleStyle: styles.title,
    textStyle: styles.text,
    imageStyle: styles.image,
    backgroundColor: '#2979FF',
    backgroundImage: intro3,
  },
  {
    key: 'k4',
    title: 'Flight Bookings',
    text: ' Best Deals on Flights',
    image: logo,
    titleStyle: styles.title,
    textStyle: styles.text,
    imageStyle: styles.image,
    backgroundColor: '#1DE9B6',
    backgroundImage: intro4,
  },
  {
    key: 'k5',
    title: 'Restaurant Bookings',
    text: ' 20% off on first Restaurant booking',
    image: logo,
    titleStyle: styles.title,
    textStyle: styles.text,
    imageStyle: styles.image,
    backgroundColor: '#FF3D00',
    backgroundImage: intro5,
  },
];
```

**Comment by Jacse** [comment]
Whoops my bad. Try this:
```js
_renderItem = ({ item, dimensions }) => (
    <ImageBackground
      source={item.backgroundImage}
      style={[
        styles.mainContent,
        dimensions
      ]}>
      {item.title}
      {item.text}
    </ImageBackground>
  );
```

**Comment by rodionovich221** [comment]
> Whoops my bad. Try this:
> 
> ```js
> _renderItem = ({ item, dimensions }) => (
>     <ImageBackground
>       source={item.backgroundImage}
>       style={[
>         styles.mainContent,
>         dimensions
>       ]}>
>       {item.title}
>       {item.text}
>     </ImageBackground>
>   );
> ```

Wow Awesome!
It's working now!
Thank you so much.
Appreciated!
