### ISSUE TITLE
Full screen slider (including status bar) on Android 9

### ISSUE THREAD

**Issue by tabekg** [Jacse/react-native-app-intro-slider#136]

**Comment by Jacse** [comment]
Could you elaborate on what you are trying to achieve?

**Comment by tabekg** [comment]
![Screenshot_2019-07-31-18-07-26-209_com docs](https://user-images.githubusercontent.com/17965311/62210597-57d13f80-b3be-11e9-8d33-86613bb37d06.png)

Please, look at the status bar. I'd like to make an intro with full-screen mode (including status bar)

**Comment by Jacse** [comment]
How about using the statusbar-component in `renderItem`? E.g.
```js
_renderItem = ({ props, dimensions }) => (
    <View
      style={[
        styles.slide,
        ...dimensions,
        backgroundColor: props.backgroundCOlor
      ]}>
          <StatusBar backgroundColor={props.backgroundColor} barStyle="light-content" />
          {props.title}
          {props.text}
    </View>
  );
```

**Comment by Jacse** [comment]
For future reference this can be achieved by doing:
```js
<View style={{flex: 1}}>
     <StatusBar translucent backgroundColor="transparent" />
     <AppIntroSlider .../>
</View>
```
