### ISSUE TITLE
Disable pagination dots click

### ISSUE THREAD

**Issue by marcolangebeeke** [Jacse/react-native-app-intro-slider#138]
Hi guys, nice component, tnx!

Would it be possible to prevent navigation by clicking on the pagination dots? (like it is possible to disable swiping using scrollEnabled={false} attribute of the FlatList)

Tnx,
Marco

**Comment by danstepanov** [comment]
I've played around with replacing the TouchableOpacity with just a View component as well as disabling the TouchableOpacity but no such luck. Not clear on what part of the dots makes them clickable but it isn't the individual dots that are clickable, it's the entire container. For reference, I believe this all happens around https://github.com/Jacse/react-native-app-intro-slider/blob/3a2769a51ee558f308bcf2fc8329fdb7932e71eb/AppIntroSlider.js#L159

**Comment by marcolangebeeke** [comment]
Thanks Dan, I will have a look and let you know if I can see a fix.

**Comment by Jacse** [comment]
This should definitely be an option - and I'm actually not sure about the clickability of the dots in general. What do you think? Should they be clickable by default, clickable with an option or maybe not clickable at all?

**Comment by danstepanov** [comment]
I think that, unless each individual dot is clickable (also allowing for going back), then the dots should not be clickable.

**Comment by marcolangebeeke** [comment]
I think it should be possible to click the dots, and it could be made configurable, not sure about it should be enabled by default..

**Comment by danstepanov** [comment]
I think it's reasonable for it just to not be enabled by default. Enable it by supplying `dotClickEnabled` or `dotPaginationEnabled`

**Comment by marcolangebeeke** [comment]
In my case I'm not using it for an intro of an app, but for a step-by-step on-boarding of an app. In each step/slide it can be configured if the data that needs to be entered is optional or mandatory, so if I can't disable the onPress on the dots, at least I would like to be able to control them (if the user entered the data in the current step, he is allowed to click on the next dot for example). That's also why I disabled swiping on the underlying FlatList component. But then again, my case might be quite specific.. :)

**Comment by danstepanov** [comment]
I am using this library for the same purpose, actually. I also added support for a `StartButton` which i'll open a PR for later this week.

**Comment by fatemafreezewala** [comment]
Use Prop `dotClickEnabled` and assign it to false
