### ISSUE TITLE
Design issue on android when the navigation bar is hidden

### ISSUE THREAD

**Issue by XavierLeTohic** [Jacse/react-native-app-intro-slider#14]
Hello there,

I choosed to hide automatically the navigation bar on my phone, as you can see on the screenshot below the space allocated to the navigation bar are still there. (Android 7.1, Samsung Galaxy S8 Plus)

I tried to make a custom renderItem method and set "paddingBottom" to 0 but it didn't work... 

```javascript
    _renderItem = (props) => {

        const style = {
            backgroundColor: props.backgroundColor,
            paddingTop: props.topSpacer,
            paddingBottom: 0
        }

        return (
            <View style={[styles.mainContent, style]}>
                <Text style={styles.title}>{props.title}</Text>
                <Image source={props.image} style={props.imageStyle} />
                <Text style={styles.text}>{props.text}</Text>
            </View>
        )
    }
```

Any ideas ?

![screenshot_20180108-233345](https://user-images.githubusercontent.com/6340490/34696216-301d2dec-f4ce-11e7-95a9-842af44eb5cc.png)

**Comment by Jacse** [comment]
The `paddingBottom` only pushes the content up so it isn't placed underneath the pagination; the background isn't affected. On the face of it, it looks like the `mainContent` isn't taking up all the space it ought to. Does the same thing happen without a custom render function?

**Comment by XavierLeTohic** [comment]
Yes the same thing happen without a custom render function :(

**Comment by aemdy** [comment]
Experiencing the same issue here, just background behind is white in my app and user can't see Skip/Next/Done buttons at all :(

**Comment by Jacse** [comment]
@XavierLeTohic which library are you using to hide the navigation bar? I'm guessing `Dimensions.get('window')` is returning the wrong height.

**Comment by aemdy** [comment]
I am using `react-native-navigation`

**Comment by Jacse** [comment]
@aemdy Is yours the same issue with a hidden software navigation bar? If not, I'd be great if you could just open a new issue. If you could post a screenshot that'd be great too.

**Comment by Jacse** [comment]
@XavierLeTohic okay so what I'll do is I'll move `height, width` to `DefaultSlide.js`. In that way you can define the height in a custom `renderItem`-function by using a library such as [react-native-extra-dimensions-android](https://github.com/Sunhat/react-native-extra-dimensions-android). How does that sound?

**Comment by aemdy** [comment]
I couldn’t reproduce it on emulator, but have a client’s screenshot. Not sure if it is related to navbar.
![81192ebf-f39e-4fac-9a49-cf1d811dc041](https://user-images.githubusercontent.com/1015018/34863637-6cf9577e-f7ab-11e7-8e89-9f6e49dae826.jpeg)

**Comment by Jacse** [comment]
@aemdy definitely looks like it. Did you disable the nav bar as well? How would you feel about the abovementioned fix?

**Comment by aemdy** [comment]
Yes, I have full screen introduction without a navbar. Sadly, I’m not able to reproduce it on any simulator I have, probably a real Samsung device is needed.

Not sure if proposed fix is ok or not for me as I won’t be able to test if it solves the issue.

**Comment by XavierLeTohic** [comment]
@Jacse I don't use any library to hide the navbar, it's a feature of Galaxy S8 and Galaxy S8+ (Also with LG G5, probably LG G6 and others devices).

Sorry for the delay, I will try to make find a way to fix it and make a PR.

**Comment by aemdy** [comment]
Any updates here?

**Comment by Jacse** [comment]
@aemdy I'm afraid I haven't quite figured out how to reproduce and test this. If you have any ideas please let me know.

**Comment by simocheccoli** [comment]
Same problem for me.
You can reproduce it with Samsung s8

**Comment by nelsonchen5** [comment]
I am also experiencing the same problem on a Samsung S8

**Comment by OrelExia** [comment]
Hello ! Me to on my Xiaomi Redmi Note 5

**Comment by trialsNow** [comment]
any idea why there is a white box in the top and everything is pushed down? Any ideas on how to pull the contents up and remove the white bar?
![device-2018-11-21-160021](https://user-images.githubusercontent.com/16502814/48868168-b44b7c00-eda6-11e8-97a8-40b60785fe58.png)

**Comment by giacomocerquone** [comment]
Same issue, Samsung Galaxy A8

**Comment by giacomocerquone** [comment]
@Jacse Solved removing the height property on the default slide. As of now I patched the defaultslide overriding in renderItem, could this be a solution? Or removing the height like this will cause some troubles in the future?

If this might be a solution, the only thing to do, is to remove it from DefaultSlide.js

**Comment by Jacse** [comment]
Does this still happen with the newest version in master?

**Comment by giacomocerquone** [comment]
Well 17 days ago my comment was made on the latest available version. If you didn't push any update, the answer is yes!

**Comment by damienix** [comment]
I'm facing a similar problem. It looks like on Android when StatusBar is used with translucent style, the app slider deducts top bar height from its height. This created empty background space at the bottom but other elements are positioned properly...

**Comment by knightkiddo** [comment]
I have the same issue with `react-nativation` + `react-native-app-intro-slider`.
I used the solution provided by @giacomocerquone . It was the only way to have the full height

**Comment by TomasAmaro** [comment]
[Harish Jangra](https://github.com/HarishJangra) posted a working solution as a PR just check it!
https://github.com/Jacse/react-native-app-intro-slider/pull/114
