### ISSUE TITLE
how to change dots place from bottom to after the picture?

### ISSUE THREAD

**Issue by umerchaudhary34** [Jacse/react-native-app-intro-slider#140]
how can change the dots place from bottom to under the image that I`m using and then details?

**Comment by Jacse** [comment]
I'm not quite sure what you mean here. Could you try to elaborate or maybe draw an image of what you want to achieve?

**Comment by umerchaudhary34** [comment]
Thank you very much for your replying.I have made my own slider.Thank you.

**Comment by Jacse** [comment]
Glad to hear it worked out!
