### ISSUE TITLE
second and third page stuck on the side and not centre

### ISSUE THREAD

**Issue by tal987** [Jacse/react-native-app-intro-slider#147]
the first page is centre in the middle and works fine but second and third getting weird behaviour:
it seems like there is extra space between the pages, I would like to cancel the space...
![Simulator Screen Shot - iPhone X - 2019-10-24 at 16 31 29](https://user-images.githubusercontent.com/43147644/67490794-7886f980-f67c-11e9-88ce-98c131ebceb7.png)

this is the code of the render items:

`_renderItem = (item) => {
    return (
      <View style={{justifyContent:'center',alignItems:'center',backgroundColor:'transparnet',borderRadius: 8,height: Dimensions.get('window').height * (Platform.OS == 'ios' ? .7 : .71),width: Dimensions.get('window').width * .86,}}>
        <Text style={{color:'black'}}>{item.item.title}</Text>
        <Image source={item.item.image} style={{backgroundColor:'red'}} />
        <Text style={{color:'black'}}>{item.item.text}</Text>
      </View>
    );
  }`

**Comment by Jacse** [comment]
Closing this since it's the same issue as #148 which you recently opened.
