### ISSUE TITLE
how to change the default dimensions of renderItem?

### ISSUE THREAD

**Issue by tal987** [Jacse/react-native-app-intro-slider#148]
I would like to change the dimensions of the slides to make them smaller how can I do that?

**Comment by Jacse** [comment]
I'm afraid it's currently not possible to change the dimensions to not be screen dimensions, but I would gladly accept a PR with more fluid sizing.

**Comment by tal987** [comment]
@Jacse  Im using with this library only for one page in my app, so I changed the width in line 77 at AppIntroSlider file in the node_modulo for what exactly I need and it works perfectly now.
its workaround solution, but because Im working with docker for my app I can apply the change every time...
you should consider to add this option in case I don't want the screen slide to be for all my page...

**Comment by Jacse** [comment]
Good to hear you found a solution! I will definitely consider adding it, it would be a great feature.
