### ISSUE TITLE
Feature request: prev button

### ISSUE THREAD

**Issue by jamesholcomb** [Jacse/react-native-app-intro-slider#15]
Thanks for putting this repo together.  I switched to it from react-native-swiper.

Additionally, would be great there was an option to disable the done button (in my scenario, there is a static OAuth connect button that is visible in each slide).

**Comment by eriveltonelias** [comment]
@jamesholcomb 

I submitted a PR. You can check it on #16 and in the docs #17

**Comment by jamesholcomb** [comment]
Thanks for the PR @eriveltonelias, I worked around it by using `renderDoneButton={() => <Text />}`

**Comment by jamesholcomb** [comment]
Per the issue title, a prevButton would be handy.

**Comment by Jacse** [comment]
@jamesholcomb does `renderDoneButton={() => null}` work for you, alternatively? I think hiding the done-button and rendering a previous button are both edge cases not often used. I'm not sure if we should add support for them in the library yet.

If we were to add a `showPrevButton`-prop how'd you expect it to behave? I was thinking:
* If `showSkipButton === true` show the skip-button on the first slide, prev-button on the rest
* If `showSkipButton === false` show the prev-button on all slides

**Comment by jamesholcomb** [comment]
I haven't tested that, but that should work.

The behavior you documented is fine, though for second bullet only show prevButton on slide > index=0.
