### ISSUE TITLE
nextbutton

### ISSUE THREAD

**Issue by sasindroid** [Jacse/react-native-app-intro-slider#150]
I am trying to customise the next button using the prop `renderNextButton`.
In my custom `renderNextButton`, is there any way to hook up the button's onPress to the nextSlide?

```
renderNextButton = () => {
  return (
    <button onPress={() => customGoToNextSlide()}>Continue</button>
  );
};
  
<AppIntroSlider
  renderItem={this._renderItem}
  slides={slides}
  onDone={this._onDone}
  bottomButton
  renderNextButton={this.renderNextButton}
/>
```

**Comment by philipp65** [comment]
Try disabling the default implementation with `showNextButton={false}`, then implementing your own slide layout and `Button` inside the `renderItem` method. You can use the `goToSlide` method to manually trigger sliding.

**Comment by jaajapie** [comment]
how to use goToSlide have example?

**Comment by jaajapie** [comment]
> Try disabling the default implementation with `showNextButton={false}`, then implementing your own slide layout and `Button` inside the `renderItem` method. You can use the `goToSlide` method to manually trigger sliding.

how to use goToSlide have example?

**Comment by philipp65** [comment]
Sure, here's a working example:

```js
<>
  <AppIntroSlider ref={component => {this.refSlider = component}} showPrevButton slides={slides} .../>                    
  <Button title={"asdfasdf"} onPress={()=>this.refSlider.goToSlide(2)}/>
</>
```

**Comment by Drzaln** [comment]
Anyone have clue with this? I have try @philipp65 method, but not as expected

**Comment by Drzaln** [comment]
I have solved this, since the button component already using TouchableOpacity, you should't using another clickable component, just use regular component such View, and Text

**Comment by philipp65** [comment]
> I have solved this, since the button component already using TouchableOpacity, you should't using another clickable component, just use regular component such View, and Text.
> 
> CMIIW

Since the `Button` is outside the `AppIntroSlider` component I don't see a problem with the solution given. Also haven't tested it out right now, but it definitely worked when I answered initially.

Glad you got it working

**Comment by ncesar** [comment]
> Sure, here's a working example:
> 
> ```js
> <>
>   <AppIntroSlider ref={component => {this.refSlider = component}} showPrevButton slides={slides} .../>                    
>   <Button title={"asdfasdf"} onPress={()=>this.refSlider.goToSlide(2)}/>
> </>
> ```

how can this be done with hooks?

**Comment by abdulrehmankfueit** [comment]
You can do this way in hooks
 const sliderRef = useRef(null);
 sliderRef.current.goToSlide(2);
