### ISSUE TITLE
Absolute positioning for intro

### ISSUE THREAD

**Issue by summerkiflain** [Jacse/react-native-app-intro-slider#151]
Hi there!

I need to display the intro on top of my app layout, please add a way to supply style prop for top most container of app-intro. Thanks.

**Comment by Jacse** [comment]
Doesn't it work if you simply wrap the component in a `View` that's absolutely positioned?

**Comment by summerkiflain** [comment]
Hi @Jacse, That exactly how I did it later in my app, I was just looking for a built-in way to do that without the need of nesting it in another view. thanks.
