### ISSUE TITLE
LinearGradient is broken in the current expo sdk

### ISSUE THREAD

**Issue by razzfox** [Jacse/react-native-app-intro-slider#159]
The current example does not work in the latest release of expo (I am using 36.0.0)

See: https://stackoverflow.com/questions/58080826/expo-lineargradient-not-working-correctly

The docs suggested workaround is to use `expo-linear-gradient` as a dependency.  

Docs:  https://docs.expo.io/versions/latest/sdk/linear-gradient/

**Comment by NickRance** [comment]
This worked for me, Thanks @razzfox !

**Comment by Jacse** [comment]
I'm closing this since the examples will be moving away from Expo
