### ISSUE TITLE
Bottom buttons and dots vertical align differently on different iPhone models

### ISSUE THREAD

**Issue by bscaspar** [Jacse/react-native-app-intro-slider#161]
First - thanks for publishing this! It's exactly what I needed for my app intro. 

Here's a screenshot of the issue - iPhone 11 on the left, iPhone 11 Pro on the right. 
<img width="801" alt="Screen Shot 2020-01-03 at 4 31 35 PM" src="https://user-images.githubusercontent.com/6042704/71755232-e3a43780-2e46-11ea-9ebf-3d9fc6785ab9.png">

Based on my testing, the buttons and dots are higher on the 11 Pro, X, and XS. They are lower (which I think is the ideal alignment) on the 11, XS Max, XR, 8, 8 Plus, and 11 Pro Max.

Here's the Snack I used to create this: https://snack.expo.io/@bcaspar/privileged-pastry

Edit: looks like `const isIphoneX` may be to blame - not sure it's picking up the appropriate phones. Anyway, by overriding the style by adding `paginationStyle={{bottom: 16}}` fixes the issue for the phones I identified above, and is included (commented out) in the snack.

**Comment by Imran-cse** [comment]
Same issue on anroid phones also

**Comment by rphansen91** [comment]
+1 on this the `paginationStyle` is also undocumented

**Comment by Jacse** [comment]
> +1 on this the `paginationStyle` is also undocumented

Do you experience this on version `4.0.0`?

**Comment by Jacse** [comment]
I'm going to close this for now. Please reopen if this is still an issue on the latest version.
