### ISSUE TITLE
AppIntroSlider is not showing inside View tag

### ISSUE THREAD

**Issue by stardev24** [Jacse/react-native-app-intro-slider#165]
Team,
If I place AppIntroSlider inside <View> tag I am getting blank screen.

I want to place my signin button and AppIntroSlider in same component.
How can I solve this problem?

**Comment by Jacse** [comment]
Could you post some minimal reproducible code and potentially a screenshot?

**Comment by Jacse** [comment]
Closing this for now. Please reopen and provide some reproducible code if you still need help
