### ISSUE TITLE
Tapping pagination dots greater than 10 (just after loading) only scrolls to index 10

### ISSUE THREAD

**Issue by razzfox** [Jacse/react-native-app-intro-slider#166]
We encountered this problem when our list had 13 slides, and tapping dots 11, 12, or 13 only scrolled to slide 10, when tapping for the first time from the first few indices.

The reason is that FlatList was only loading 10 slides to start, so the slides above 10 had not been loaded yet, but the pagination dots still attempt to scroll to them.

Our solution was to pass this option through to the FlatList:
`initialNumToRender={slides.length}`

I think that this is a bug in this component, because since the pagination dots exist and are tappable, it it a bug that they do not scroll to the tapped slide. Also, we do not have a skip button, so the user will always go through all of the slides, so the "number to render" optimization is mute without a skip button.

**Comment by Jacse** [comment]
Good point. Closed by 2f790cca8efd76dad0958c8e959230a945501bab
