### ISSUE TITLE
can not move the dots left side of the screen. and paginationStyle is not working 

### ISSUE THREAD

**Issue by hiren0412** [Jacse/react-native-app-intro-slider#167]
<AppIntroSlider
                    renderItem={(item) => this.renderItem(item)}
                    slides={slides}   
                    // ref={component => {this.refSlider = component}}                 
                    dotColor={StyleConfig.lighter_grey}
                    activeDotColor={StyleConfig.blue_light}
                    paginationStyle={{textAlign:'left'}}
                    renderNextButton={this._renderNextButton}
                    renderDoneButton={this._renderDoneButton}

                />

**Comment by Jacse** [comment]
Hi @hiren0412 could you maybe provide some more information so I can try to reproduce this?

**Comment by Jacse** [comment]
I'm going to close this for inactivity. Let me know if you stille experience the issue.
