### ISSUE TITLE
Create Custom Bottom Button

### ISSUE THREAD

**Issue by ramkumarb** [Jacse/react-native-app-intro-slider#171]
Hi,

 I am trying to implement two custom buttons at the bottom, is it possible to do that?
![Screen Shot 2020-02-20 at 1 05 56 PM](https://user-images.githubusercontent.com/7746172/74911045-d4228300-53e1-11ea-8d6a-0b86d005bb81.png)

**Comment by Jacse** [comment]
Not currently, I'm afraid.

**Comment by Jacse** [comment]
Actually, this is now supported. You can take a look at the example [here](https://github.com/Jacse/react-native-app-intro-slider/blob/master/examples/examples/CustomPagination/index.js)

**Comment by AyushP851** [comment]
> Actually, this is now supported. You can take a look at the example [here](https://github.com/Jacse/react-native-app-intro-slider/blob/master/examples/examples/CustomPagination/index.js)

link not working

**Comment by Jacse** [comment]
My bad! Updated the link.

**Comment by markgrancapal** [comment]
Can we also customize the button on top of each other?
