### ISSUE TITLE
Can no longer customise colour of label text

### ISSUE THREAD

**Issue by cameronmurphy** [Jacse/react-native-app-intro-slider#179]
With the update to 4.x I can no longer change the Next / Skip / Back / Done label text to black, as we have white slides in our app intro.

Previously we were able to use the `buttonTextStyle` prop and now this is gone.

Please provide some kind of upgrade guide and information as to how to restore 3.x functionality.

**Comment by Jacse** [comment]
Hi @cameronmurphy,

Upgrade guide is under [releases](https://github.com/Jacse/react-native-app-intro-slider/releases/tag/v4.0.0).

What you can do now is define render functions like so:
```js
_renderDoneButton = () => <Text style={styles.buttonText}>Done</Text>
_renderNextButton = () => <Text style={styles.buttonText}>Next</Text>

return <AppIntroSlider renderDoneButton={this._renderDoneButton} renderNextButton={this._renderNextButton} />

```

**Comment by cameronmurphy** [comment]
Ah thank you! The upgrade guide should mention that `slides` prop is now called `data` :)

**Comment by Jacse** [comment]
> Ah thank you! The upgrade guide should mention that `slides` prop is now called `data` :)

Yes of course! Fixed

**Comment by Jacse** [comment]
I'm going to close this since it seems resolved. Let me know if other issues arise!
