### ISSUE TITLE
Error Data.Length in IntroSlider.JS

### ISSUE THREAD

**Issue by zapcriativo** [Jacse/react-native-app-intro-slider#180]
Hi,

After updating the Expo version, the following error is returning in the component. Can you help me please?

**TypeError: undefined is not and object (evaluating: 'data.length')

This error is located at:
in AppIntroSlider (at IntroSlider.js: 135)**

**Comment by dungphung** [comment]
Hey man. Change to new version slides in AppIntroSlide to data like this 
 <AppIntroSlider
          renderItem={this.renderContentSlider}
          data={slides}
          keyExtractor={this._keyExtractor}
 />

**Comment by zapcriativo** [comment]
Hi, it worked .. Thank you so much !!

But buttonStyle is no longer working, did you change the name of the props?

**Comment by Jacse** [comment]
> But buttonStyle is no longer working, did you change the name of the props?

`buttonStyle` has been removed in favor of using the `renderDoneButton`/`renderNextButton` etc. functions. You can find out more about the release under [release notes](https://github.com/Jacse/react-native-app-intro-slider/releases/tag/v4.0.0).

Hope it makes sense!

**Comment by Jacse** [comment]
Closing this since it seems to be resolved
