### ISSUE TITLE
Cannot run AppIntroSlider because of TypeError

### ISSUE THREAD

**Issue by smeusling** [Jacse/react-native-app-intro-slider#182]
I just install react-native-app-intro-slider and I have the following error when running my app :
<img width="374" alt="Screenshot 2020-04-10 at 21 49 54" src="https://user-images.githubusercontent.com/2088127/79018933-596e1c80-7b75-11ea-80dd-055afb3d7094.png">

**Comment by Jacse** [comment]
You need to supply the slides using the `data`-prop, which was renamed from `slides` in version 4. You can find the release notes under [releases](https://github.com/Jacse/react-native-app-intro-slider/releases/tag/v4.0.0)

**Comment by smeusling** [comment]
Great, thanks, I didn't notice the change of prop name, oups
Have a nice day

**Comment by Jacse** [comment]
You too!
