### ISSUE TITLE
dist/index.js missing

### ISSUE THREAD

**Issue by RauanBPK** [Jacse/react-native-app-intro-slider#183]
`/node_modules/react-native-app-intro-slider/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved..

indeed, no dist/index.js

![image](https://user-images.githubusercontent.com/30680760/79373343-d2ca8e00-7f2c-11ea-8859-2bedf7f5d0d4.png)

**Comment by Luis-Kendelick** [comment]
Man, have you tried to change the reference name in the package.json file? Cause in the .json has a ".js" reference instead the ".d.ts".

**Comment by thubamamba** [comment]
Once you change the file index file type to .js, you get this error:

<img width="246" alt="Screenshot 2020-04-15 at 21 34 33" src="https://user-images.githubusercontent.com/22769109/79380641-fb6c7b00-7f60-11ea-8f92-89dd868dc871.png">

**Comment by devamiya** [comment]
Same issue....is anyone previously used this

**Comment by Jacse** [comment]
It looks like I somehow forgot to build the `index.js`-file before publishing to npm, really sorry! I've [updated](e04d4c8ac3348f207a95d57946a2441e437fd17f) the scripts so that won't be possible in the future. Please try with the latest version on npm.

**Comment by thubamamba** [comment]
Thank you so much @Jacse , it works perfectly.
