### ISSUE TITLE
How can i have skip button on the last slide?

### ISSUE THREAD

**Issue by guitorioadar** [Jacse/react-native-app-intro-slider#185]
I know the onDone will do the same but i need to have skip button on that page as well. Can anyone help me with that?

**Comment by Jacse** [comment]
May I ask why? Normally the skip button just goes to the last page which wouldn't really make sense given that you are already on the last page.

**Comment by guitorioadar** [comment]
yes i know and i have already mentioned that...  but in my design i need to implement this skip button... is there any way to add ad function on the previous button or something?

**Comment by Jacse** [comment]
You could defined your own pagination component using `renderPagination`. That would give you full control over which buttons are displayed when.
