### ISSUE TITLE
PrevButton and NextButton functionality?

### ISSUE THREAD

**Issue by guitorioadar** [Jacse/react-native-app-intro-slider#186]
Is there any like onNextButtonPress or onPreviousButtonPress function available... cos i need to do something with that... thanks

**Comment by Jacse** [comment]
Did you consider `onSlideChange`? That will be called every time the user navigates to one of the other slides.

**Comment by SherozeAli** [comment]
Hi there !
Just remove the button(ButtonContainer) from renderNextButton just use the View
like

![image](https://user-images.githubusercontent.com/57250312/81899449-4b784500-95d4-11ea-955d-f9bdaf8ae9a8.png)


Button will not work here !
This works for me
Make view& Text looks like button style yourself

**Comment by Jacse** [comment]
Will `onSlideChange` work for you @guitorioadar? I'm going to close this for now, but let me know if I should reopen.
