### ISSUE TITLE
renderNextButton not working, when using renderPagination.

### ISSUE THREAD

**Issue by TamerlanG** [Jacse/react-native-app-intro-slider#187]
<h1> Description </h1>
As the title says, when you use renderPagination, then renderNextButton just doesn't render my custom button.

```
const  renderItem  =  ({item})  => {
  return  <SlideManager current_slide={item.name} />;
};

const  renderNextButton  =  ()  => {
   return (
	  <ButtonContainer>
		  <AppIntroButton  />
	  </ButtonContainer>
   );
};

const  renderPagination  =  index  => (
  <PaginationContainer>
    <Pagination  size={slides.length} current={index} />
  </PaginationContainer>
);

  
return (
<>
  <AppIntroSlider
    data={slides}
    showNextButton 
    renderPagination={renderPagination}
    renderItem={renderItem}
    renderNextButton={renderNextButton}
   />
</>

);

```

<h2> Version </h2>
"react-native": "0.62.2"
<br/>
"react-native-app-intro-slider": "^4.0.2"

**Comment by SherozeAli** [comment]
Hi there !
Just remove the button(ButtonContainer) from renderNextButton just use the View 
like
const  renderNextButton  =  ()  => {
   return (
	  <View>
		  <Text>Next</Text>
	  </View>
   );
};


Button will not work here !
This works for me 
Make view& Text looks like button style yourself

**Comment by SherozeAli** [comment]
![image](https://user-images.githubusercontent.com/57250312/81899242-cdb43980-95d3-11ea-85c2-b7c96a8437ca.png)


Hi there !
Just remove the button(ButtonContainer) from renderNextButton just use the View
like in screenshot
Button will not work here !
This works for me
Make view& Text looks like button style yourself

**Comment by TamerlanG** [comment]
@SherozeAli If it's a view then I cannot press it, I believe it should be a touchable opacity

**Comment by SherozeAli** [comment]
> @SherozeAli If it's a view then I cannot press it, I believe it should be a touchable opacity
@TamerlanG 
I only accepts View bcz of its pre-defined functionality !
button click won't work !
it has its own listener !

**Comment by Jacse** [comment]
`renderPagination` covers both the pagination dots and any buttons, so if you want to render buttons you should do so inside the `renderPagination`-function. I'll make sure to update the README to document this better.

**Comment by SherozeAli** [comment]
@Jacse cool !
This is for all those who're having some difficulty related to this custom button

In my case what i figured out 
 button don't work but View does(already mentioned in screenshot ) !
