### ISSUE TITLE
argument type of `renderItem` should be ItemT

### ISSUE THREAD

**Issue by pke** [Jacse/react-native-app-intro-slider#191]
This is great library! It has every customisation feature I'd hoped for! Kudos! 🚀 

One little question though re the `renderItem` render function:
Its currently defined as: `renderItem: (a: any) => React.ReactNode;`
wouldn't it be possible to define it as `renderItem: (a: ItemT) => React.ReactNode;`?

**Comment by Jacse** [comment]
Absolutely! Let me know if it looks good on version `4.0.4`

**Comment by pke** [comment]
Somehow even though the typedefs are correct now, VSCode still complains.
![image](https://user-images.githubusercontent.com/164625/83271936-cfcce980-a1ca-11ea-9608-0b8f0b3a23c5.png)

But as you can see I have defined a type named `Item` like this:

```ts
type Item = {
  id: string
  title: string
  text: string
  image: ImageSourcePropType
}
```

Could that be a caching problem?
