### ISSUE TITLE
is there a way to style the next button ?

### ISSUE THREAD

**Issue by abhidj0090** [Jacse/react-native-app-intro-slider#209]

**Comment by kg-kartik** [comment]
Yes, you have to manually change the style by changing it in the package files itself.
You can go to the node_modules/react-native-app-intro-slider/dist/index.js.
And in the index.js file go to the styles part and edit the styles variable 'buttonText` according to your needs.
Though, the particular style is for all the bottom texts: skip,next and done.

**Comment by AguilarJorge** [comment]
@abhidj0090  in the **renderNextButton** prop call the function thats render your custom button

```
const _renderCustomNextButton = () => {
    return (
        <View style={{ borderRadius: 20, overflow: 'hidden' }}>
            <Text style={{
                color: 'red',
                padding: 20,
                ...
            }}>Custom Style Button</Text>
        </View>
    );
};

<IntroSlider renderNextButton={ _renderCustomNextButton } />
```

**Comment by Jacse** [comment]
Closing this since it seems answered
