### ISSUE TITLE
titleStyle and textStyle not working

### ISSUE THREAD

**Issue by Jingo91** [Jacse/react-native-app-intro-slider#25]
Im using the basic example slider.
This is how i add my slider:

const slides = [

	{
		key: 'welcome',
		title: 'Welcome to My App',
		titleStyle: {
			color:"green"
		},
		text: 'Hello you are welcome',
		textStyle: {
			color:"red"
		},
		image: require('../assets/Logo.png'),
		imageStyle:  {
			width: 250,
			height: 325,
			resizeMode: 'contain'
		},
		backgroundColor: '#fff'
	}
]

But the text color is not changing. Am i doing something wrong?

**Comment by Jacse** [comment]
Are you using the latest version of `react-native-app-intro-slider`? I just tested the example setup and it works on my end.

**Comment by dblazeski** [comment]
Had the same issue, after installing the latest version using yarn. Looks like the version here on git is not the same as react-native-app-intro-slider.
Copying DefautSlider.js from git fixed the issue.

**Comment by Jacse** [comment]
Try updating it now, I just released version 0.2.4. I guess something went wrong the first time.

**Comment by dblazeski** [comment]
Worked for me with the new version, had to delete node_modules and install again though - some cache issue.

**Comment by Jacse** [comment]
Great!
