### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'AppIntroSlider

### ISSUE THREAD

**Issue by vbagustinus** [Jacse/react-native-app-intro-slider#29]
I using 
```
"react": "15.4.2",
 "react-native": "0.41.2",
```
 got
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'AppIntroSlider'`
but worked with new version.
![rnslider](https://user-images.githubusercontent.com/17118867/37503077-d8ce0998-2908-11e8-801c-37ffe25351c2.png)

**Comment by Jacse** [comment]
The library uses FlatList, which was only introduced in version 0.43.0 or 0.44.0. You'll have to use a React Native version newer than that.
