### ISSUE TITLE
Does this support uri images?

### ISSUE THREAD

**Issue by llamorinjason** [Jacse/react-native-app-intro-slider#32]

**Comment by webcoweb** [comment]
Hello,

at first thanks dear @Jacse  for **react-native-app-intro-slider** , I think it`s perfect.
And dear @llamorinjason you are free to use both **uri** and **require** image path as follows
: 

image: require('./assets/1.jpg'),
**OR**
image: { uri : 'http://www.tutorialsee.com/sites/default/files/ScreenShort/IntroSlider1.png'},

**Comment by llamorinjason** [comment]
Yes, I already got it, but thanks for replying, appreciate it 👍
