### ISSUE TITLE
How customize the Next, Back and Done button color, default is white

### ISSUE THREAD

**Issue by vvavdiya** [Jacse/react-native-app-intro-slider#34]
My main screen color is white, So Next, back and done button text/title color is white by default. So, these buttons are not visible. How can we change the text/title color of these buttons?

![simulator screen shot - iphone 6 - 2018-04-05 at 15 36 57](https://user-images.githubusercontent.com/4570688/38360322-6b22d11e-38e7-11e8-9c82-ba45f56cbf1d.png)

**Comment by Jacse** [comment]
I suggest you use the `renderNextButton` etc. props. If you want to change the color as the active slide is chaingin I suggest to use state and listen to `onSlideChange`

**Comment by golles** [comment]
A solution that I would also appreciate is that both `styles.bottomButton.backgroundColor` and `styles.buttonText.backgroundColor` could be set by the user.
However they are only used by 2 out of the 4 buttons...

**Comment by Jacse** [comment]
@golles I'm honestly not a big fan of adding so many new props. To keep it much more customizable I prefer that people implement their own `render{x}Button`-methods.

**Comment by Jacse** [comment]
@vvavdiya let me know if my approach does not work for you.

**Comment by CodeBunny786** [comment]
HI @Jacse How can i achieve this please guide how can i change colour of NEXT skip button etc

**Comment by CodeBunny786** [comment]
Please Guide me Thanks

**Comment by UsmanRana77** [comment]
There is no option to handle from the main component so I find the solution Just go 
(node_modules/react-native-app-intro-slider/Appslider.js) you can customize each and everything from this file 

Thanks
