### ISSUE TITLE
Slider is buggy on Android, does not scroll easely.

### ISSUE THREAD

**Issue by hugoh1995** [Jacse/react-native-app-intro-slider#36]
The slider is very buggy on Android, I have multiple users reporting that they can not scroll through the slider or have to go to the very edge of the screen and scroll slowly to the opposite side in order to scroll to the next slide.

**Comment by Jacse** [comment]
Hi @hugoh1995. Are you sure this is an issue with this component and not somehting else? Which Android versions are you getting reports on? Is it reproducible?

**Comment by Jacse** [comment]
I'm not experiencing this on my OnePlus 3T. Does it happen if you run the example?

**Comment by hugoh1995** [comment]
Actualy this was probably due to the fact that I twicked some part of the library to change the positioning of some elements. If I try with the example, it does not bug. I will close this issue. Thank you!
