### ISSUE TITLE
Enhancement suggestion: Provide default styles override option

### ISSUE THREAD

**Issue by therealgilles** [Jacse/react-native-app-intro-slider#37]
It would be great if the default styles could be easily overridden. Something like:

```
  constructor(props) {
    super(props)

    this.state.styles = { styles, ...props.styles }
  } 
```

and then use this.state.styles instead of styles in the code. Right now, it's a little cumbersome to have to provide a new render function just to change the style of a skip/next/done text button.

Thanks!

**Comment by Jacse** [comment]
I have now added `dotStyle`, `activeDotStyle`, `buttonTextStyle`, and `buttonStyle` to props, hope that covers it.
