### ISSUE TITLE
Dragging issue in slider

### ISSUE THREAD

**Issue by cerberusv2px** [Jacse/react-native-app-intro-slider#4]
I encountered this issue while sliding the intro screen.

it says Unsupported top level event type dispatched

https://github.com/facebook/react-native/issues/16900

**Comment by Jacse** [comment]
It's an issue with React Native that they are still trying to solve. Check issue [#16522](https://github.com/facebook/react-native/issues/16522) for more info.

Hopefully it will be fixed in version `0.50.4` - I'll leave this issue open until then.

**Comment by Jacse** [comment]
This is fixed in `0.50.4`
