### ISSUE TITLE
Invalid return type

### ISSUE THREAD

**Issue by WilhelmErasmus** [Jacse/react-native-app-intro-slider#40]
I'm attempting to use your library but I am getting this warning and the slider does not render.

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AppIntroSlider`.

```
import React, { Component } from 'react';
import { StyleSheet } from 'react-native';
import AppIntroSlider from 'react-native-app-intro-slider';

export default class Example extends Component {
  _onDone = () => {
    this.props.navigator.pop()
  }
  render() {
    return <AppIntroSlider slides={slides} onDone={this._onDone} showSkipButton bottomButton/>;
  }
}
```

I have also defined the slides variable according to the README docs.

**Comment by Jacse** [comment]
Did you install the library using npm/yarn?

**Comment by WilhelmErasmus** [comment]
NPM

**Comment by Jacse** [comment]
Strange. Does the example work for you?

**Comment by Jacse** [comment]
Could you post those errors?

**Comment by WilhelmErasmus** [comment]
So when I run it and I try to use it using 

```
render() {
render(<View><AppIntroSlider
      slides={slides}
      onDone={this.props.onDone}
      showSkipButton
/></View>);
}
```

I get this warning and the intro screen doesn't render:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of 'AppIntroSlider'.
```

**Comment by WilhelmErasmus** [comment]
With regards to the example, see #41

**Comment by Jacse** [comment]
And as I said in #41, the error you are seeing is because expo isn't invoked properly. The error message tells us that the react native version used is not the expo fork as it should be.

**Comment by WilhelmErasmus** [comment]
Thanks, I am using an older version.
