### ISSUE TITLE
Example not working properly

### ISSUE THREAD

**Issue by WilhelmErasmus** [Jacse/react-native-app-intro-slider#41]
When I clone the repo and run `yarn install` followed by `exp start` in the `./Example` directory, the app loads but I get the error "Unsupported top level event type "topScroll" dispatched when I click the "Next" button.

The `exp start` console also warns the following:

```
10:00:50 [exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
10:00:56 [exp] Warning: Installed version 0.2.3 of 'react-native-app-intro-slider' does not satisfy required version file:../
10:00:56 [exp] 
10:00:56 [exp] If there is an issue running your project, please run `npm install` in /path/to/clone/Example and restart.
```

**Comment by Jacse** [comment]
It seems expo wasn't installed properly. As described in the README, what you want to do to use the example is the following:
```
git clone https://github.com/Jacse/react-native-app-intro-slider.git
cd react-native-app-intro-slider/Example
yarn
yarn start
```

What happens if you use `yarn start` in stead of using the exp cli?

**Comment by Jacse** [comment]
It sounds like you could be using an old version of React Native - at least you're not using the version that expo would like. Please see #29.

**Comment by WilhelmErasmus** [comment]
Thanks, I am using an older version.
