### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by developdeez** [Jacse/react-native-app-intro-slider#42]
Example doesn't work and it isn't clear how to change the images or anything.

**Comment by Jacse** [comment]
Hi @developdeez 

This issue is a little unhelpful. How exactly is the example not working?

You change the images by simple replacing the files and changing the url.

**Comment by Jacse** [comment]
Could you post the error message here?

**Comment by danikane** [comment]
https://snack.expo.io/@danikane/appintro
