### ISSUE TITLE
Add prop to disable touch scrolling

### ISSUE THREAD

**Issue by krewllobster** [Jacse/react-native-app-intro-slider#46]
Hi, and thank you for this component! I'm re-purposing it for a multi-page form and I think two **relatively** small changes would do it: 

1. It would be great to be able to pass a `scrollEnabled={false}` prop such that touch scrolling is disabled.
2. In order to work with #1, having an exposed function onNext which by default is just:
`() => true` by default, but could be over-ridden with a function that returns a boolean. On false, the slide is not advanced. 

These two combined will allow for form validation on the current page!

**Comment by Jacse** [comment]
Wouldn't it be sufficient with at `disabled` prop that disables both buttons and scrolling behaviour? You can then set the prop to true when the form is invalid and only allow users to progress after validation. The difference from your suggestion is that users can both click the buttons and scroll the pages to go forward.

**Comment by krewllobster** [comment]
yep, you're absolutely correct! That would allow disabled to be set to a function that runs validation, or whatever you need. Good call :)

**Comment by krewllobster** [comment]
In thinking about it though, it may be nice to have a scrollEnabled prop, just in case someone wants only the buttons to be able to progress, not swipes. That should be simple to expose in the component as well.

**Comment by Jacse** [comment]
How about passing all props to the underlying FlatList, e.g. `scrollEnabled`?

**Comment by Jacse** [comment]
Since 4aeca4a780c543ab667e724ed0885ca9dd1e0197 the library simply extends flatlist, so you can pass `scrollEnabled` to it easily. At the same time, you can use custom renderbutton functions to enable/disable buttons.
