### ISSUE TITLE
Is there a way to customize each slide???

### ISSUE THREAD

**Issue by rosman21** [Jacse/react-native-app-intro-slider#48]
Is there a way that you code out your slides separately? For example, I want to have different styles for each slide, so I would want my files to be like firstSlide.js, secondSlide.js etc

**Comment by Jacse** [comment]
Yes, you'd want to use the `renderItem`-prop to specify your own slides. It gets passed whatever you put in your slides, so you can identify each by their keys for example. You can see my response in [issue 35](https://github.com/Jacse/react-native-app-intro-slider/issues/35#issuecomment-380727811).
