### ISSUE TITLE
Pages Mess up on rotaion

### ISSUE THREAD

**Issue by doalef** [Jacse/react-native-app-intro-slider#5]
screens mess up when screen is rotated , two slides appear on the screen
![screenshot_1511613855](https://user-images.githubusercontent.com/30926429/33230598-b4ba804a-d1fb-11e7-9a1d-7022fc5e8ab1.png)

**Comment by Jacse** [comment]
I was thinking whether or not to support orientation changes, thinking that the room for actual pages would be really small on horizontal orientation due to buttons etc taking up space. I can definitely implement support, though.

Do you think it makes sense? I guess one could always choose not to render buttons.

**Comment by doalef** [comment]
it does make sense ,not many people rotate their phone when they're seeing the intro but it's still nice to have the support.

**Comment by Jacse** [comment]
Please try installing from `https://github.com/Jacse/react-native-app-intro-slider.git` and let me know if it works as expected

**Comment by doalef** [comment]
nothing changed.
![screenshot_1512396504](https://user-images.githubusercontent.com/30926429/33556685-f6dd3da8-d919-11e7-8074-4b5cab780810.png)

**Comment by doalef** [comment]
I guess you forgot to use `npm publish` , I couldn't find the changes you made in your last commit in the files I pulled from npm.

**Comment by Jacse** [comment]
No, I haven't published to npm yet, I wanted to hear if it worked for you first. Thats why I asked you to install from `master` by doing `npm i Jacse/react-native-app-intro-slider`

**Comment by doalef** [comment]
my bad sorry , I installed it and it works perfectly, thank you.

**Comment by Jacse** [comment]
@doalef great, thanks. I'll make sure to update `npm` soon.

**Comment by philipp65** [comment]
I'm still experiencing this bug (from the 2nd slide on)  if I rotate from portrait to landscape.

```
export default class S02_widgets extends React.Component {

    render() {
        return (
            <SafeAreaProvider>
                <SafeAreaView style={{backgroundColor: "#e3000f"}}/>
                <View style={styles.container}>
                    <View style={styles.title_container}>
                        <Text style={styles.title}>Title </Text>
                    </View>
                    <View style={styles.img_container} >
                        <Image style={styles.img} source={require('../../assets/img/S02_widget_ios.png')}/>
                    </View>
                    <View style={styles.text_container}>
                        <Text style={styles.text}>Description</Text>
                    </View>
                </View>
            </SafeAreaProvider>
        )
    }
}
```
