### ISSUE TITLE
Dot Position 

### ISSUE THREAD

**Issue by Mayankwebdev** [Jacse/react-native-app-intro-slider#51]
How to change dot position .

**Comment by Jacse** [comment]
This is currently not possible, where would you like to place them?

**Comment by RamdanK** [comment]
@Mayankwebdev 
the dot pagination must be separate from the bottom button..
but the next and prev button still with the pagination.. because the position of the pagination is already 'absolute'. so you can edit it as you need. sorry if I wrong. i just learn RN though :smile:

**Comment by rphansen91** [comment]
Their is an undocumented paginationStyle prop that can be used to move the dots container element @Mayankwebdev

**Comment by Jacse** [comment]
Actually that’s been removed in the newest version! It’s been replaced by a renderPagination-function, which brings more flexibility to design pagination dots and buttons exactly as you want.

**Comment by ghost** [comment]
<AppIntroSlider dotStyle={{marginBottom: '340%', backgroundColor: 'rgba(0, 0, 0, .3)'}} activeDotStyle={{marginBottom: '340%', backgroundColor: '#27A6EE'}} renderItem={this._renderItem} data={slides} renderDoneButton={this._renderNone} renderNextButton={this._renderNone}/>

try adding margin in dotStyle and activeDotStyle

**Comment by frontend-programming** [comment]
> <AppIntroSlider dotStyle={{marginBottom: '340%', backgroundColor: 'rgba(0, 0, 0, .3)'}} activeDotStyle={{marginBottom: '340%', backgroundColor: '#27A6EE'}} renderItem={this._renderItem} data={slides} renderDoneButton={this._renderNone} renderNextButton={this._renderNone}/>
> 
> try adding margin in dotStyle and activeDotStyle

 <AppIntroSlider
          renderItem={this._renderItem}
          data={slides}
          dotStyle={{backgroundColor: '#bababa', marginTop: 10}}
          activeDotStyle={{backgroundColor: '#f33a72', marginTop: 10}}
          onDone={this._onDone}
          onSkip={this._onDone}
          showSkipButton={true}
          showPrevButton={true}
          renderNextButton={this._renderNextButton}
          renderSkipButton={this._renderSkipButton}
          renderPrevButton={this._renderPrevButton}
          renderDoneButton={this._renderDoneButton}
        />

Add marginTop to shift bottom position in dotStyle and activeDotStyle.

**Comment by mindgosharma** [comment]
can we  shift  dots  horizontally?

**Comment by cave-jhonson** [comment]
> can we shift dots horizontally?

you can, by shifting with position relative like this 

dotStyle={{
            backgroundColor:'#FCFCFC', 
            width:10, 
            height:10,
            position:'relative',
            right:'50%'
          }}
          activeDotStyle={{
            backgroundColor:'#D2FA00',
            width: 42,
            position:'relative',
            right:'50%'
          }}

**Comment by EdodooSpark** [comment]
How can i turn the dots to dashes

**Comment by fee-sah-yor** [comment]
> <AppIntroSlider dotStyle={{marginBottom: '340%', backgroundColor: 'rgba(0, 0, 0, .3)'}} activeDotStyle={{marginBottom: '340%', backgroundColor: '#27A6EE'}} renderItem={this._renderItem} data={slides} renderDoneButton={this._renderNone} renderNextButton={this._renderNone}/>
> 
> try adding margin in dotStyle and activeDotStyle

you saved me today, thank you
