### ISSUE TITLE
More flexibility to override default props.

### ISSUE THREAD

**Issue by efleurine** [Jacse/react-native-app-intro-slider#53]
I think it would be great to add more flexibility in this the slider.

Like I needed to change the label text from white to black since there is no prop and the 'white' https://github.com/Jacse/react-native-app-intro-slider/blob/5ec6a7249e0cb7dda4d9caf94a5636cae9a84141/AppIntroSlider.js#L215 color is hardcoded in the stylesheet. I had to fork and to the changes in my repo. 

The defaults are great but providing ways to override the default styles would be nice.

I understand this would increase the number of available props but at the same time customization would be easier and everyone would use the same way to do.

**Comment by Jacse** [comment]
I've now added a `buttonTextStyle`-prop 🍾 Will publish to NPM asap
