### ISSUE TITLE
Slow down page change effect speed

### ISSUE THREAD

**Issue by nzhtrtlc** [Jacse/react-native-app-intro-slider#55]
Hi, here is my code the basic example.

`const Home = () => (
    <AppIntroSlider
        slides={slides}
        onDone={() => console.log('done')}
    />
)`

The problem is; when i click next or swipe it with touch it slides very fast.
Is there a way to slow down transition speed ?

**Comment by nzhtrtlc** [comment]
I've just realized the animation speed changes according to your touch type. If you touch slow and smooth it slowly slides, but if you do it more fast then animation going fast too.
So its not a big deal.
Still, i would like to learn if there is way to customize animation otherwise we can close the issue.

**Comment by Jacse** [comment]
To change the page, the library uses the underlying FlatList's [scrollToOffset](https://facebook.github.io/react-native/docs/flatlist#scrolltooffset)-function, which unfortunately does not allow for altering the duration. So currently this is not possible.

**Comment by Jacse** [comment]
To change the page, the library uses the underlying FlatList's [scrollToOffset](https://facebook.github.io/react-native/docs/flatlist#scrolltooffset)-function, which unfortunately does not allow for altering the duration. So currently this is not possible.
