### ISSUE TITLE
dotStyle & activeDotStyle props not working 

### ISSUE THREAD

**Issue by mbors** [Jacse/react-native-app-intro-slider#60]
Hello!
Thanks for this package, it's super useful!

I have an issue while using dotStyle & activeDotStyle props. I have something like this:

```
                <AppIntroSlider
                    slides={slides}
                    onDone={this._onDone}
                    renderItem={this._renderItem}
                    dotStyle={{backgroundColor: 'blue'}}
                    activeDotStyle={{backgroundColor: 'red'}}
                />
```
Unfortunately there's no change in the backgroundColor of the dots.

**Comment by Jacse** [comment]
It works on my end. Are you using the newest version of `react-native-app-intro-slider`?

**Comment by mbors** [comment]
It seems that I am not! It is working fine now, thanks!
