### ISSUE TITLE
Is there a way to manually configure the slide that appears? [Help Needed]

### ISSUE THREAD

**Issue by outdoorsole** [Jacse/react-native-app-intro-slider#63]
Hello,

I wanted to ask if there is a way to customize which slide appears (page number). I see there is a method for the AppIntroSlider 'goToSlide' that sets the page number that I would like to customize manually. There are two reasons behind this: 

(1) I am placing a custom button inside one of the slides, which will pop up a modal screen. After the modal is dismissed, I would like to be able to move to the next slide automatically without having to press the 'next' button.

(2) After the user goes through all the slides, I wanted to add the option to start over from the beginning (slide 0).

Would anyone be able to help offer suggestions on how to implement this, or if a potential workaround? Thank you!

**Comment by Jacse** [comment]
You should be able to simply use the `goToSlide`-function for your purposes using ref. After the user closes the model for example, you would call `AppIntroSlider.goToSlide(n + 1)` and if the user chooses the option to start over from the beginning you would call `AppIntroSLider.goToSlide(0)`.

**Comment by Jacse** [comment]
I'm closing this for now - let me know if it didn't work out!
