### ISSUE TITLE
props in render function is undefined

### ISSUE THREAD

**Issue by sinclas** [Jacse/react-native-app-intro-slider#65]
Hi,

Implementing the custom renderItem function and the props.colors is complaining that props is undefined.  Does the AppIntroSlider component pass these props on each slide?  

_renderItem = props=> (
  <LinearGradient
    style={[styles.mainContent, {
      paddingTop: 20,
      paddingBottom: 20,
      width: '100%',
      height: '100%',
    }]}
    colors={props.colors}
    start={{x: 0, y: .1}} end={{x: .1, y: 1}}
  >
    <Image style={{ backgroundColor: 'transparent' }} name={props.icon} size={200} color="white" />
    <View>
      <Text style={styles.title}>{props.title}</Text>
      <Text style={styles.text}>{props.text}</Text>
    </View>
  </LinearGradient>

**Comment by Jacse** [comment]
Only if you defined the `color`-property in your `slides`-array
