### ISSUE TITLE
Android swipe

### ISSUE THREAD

**Issue by GituBojan** [Jacse/react-native-app-intro-slider#66]
Hi! 

I have added 10 slides to the configuration and swiping between them works on iOS without any problems. If I swipe right or left it leads me to the next or previous slide. 

On Android there is an odd behavior. If I swipe right (or left) it changes multiples indexes immediately. It does not only continue to the next slide index but it moves much more ahead. Is there a configuration or fix I am missing for Android? 

React 0.57.1

```
<AppIntroSlider
                slides={slides}
                nextLabel={strings("HowTo.next")}
                doneLabel={strings("HowTo.done")}
                renderItem={this._renderItem}
                onDone={() => {
                    AsyncStorage.setItem("intro", "true")
                        .then(res => this.props.navigation.goBack())
                        .catch(e => console.log(e));
                }}
            />
```

**Comment by patskot** [comment]
@GituBojan did you find a solution for this? I'm experiencing the exact same issue.
