### ISSUE TITLE
this.props.navigation.navigate('Route_Name') doesn't work

### ISSUE THREAD

**Issue by urvitrivedi** [Jacse/react-native-app-intro-slider#7]
I have been trying to re-route from the app-intro-slider(Welcome Screen) to the Login Screen using the following method

render(){
_onDone=()=>{
this.props.navigation.navigate('Login')
};
return (
      <AppIntroSlider
        slides={slides}
        renderItem={this._renderItem}
        bottomButton
        onDone={this._onDone}
      />
    );
}
But it doesn't work. Please correct me as I am still a brand new to react-native.

**Comment by Jacse** [comment]
It ought to work. Could you paste more of your code?

**Comment by urvitrivedi** [comment]
const styles = StyleSheet.create({
  mainContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  image: {
    width: 180,
    height: 180
  },
  text: {
    color: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: 'transparent',
    textAlign: 'center',
    paddingHorizontal: 16,
    marginBottom: 40
  },
  title: {
    fontSize: 22,
    color: 'white',
    backgroundColor: 'transparent',
    textAlign: 'center',
    marginBottom: 16
  }
});

const slides = [
  {
    key: 'somethun',
    title: 'Create your profile',
    text: 'Introduce yourself to get started.',
    colors: ['#474973', '#ED808C']
  },
  {
    key: 'somethun1',
    title: 'Title 1',
    text: 'Add trusted friends or discover like-minded parents near you.',
    colors: ['#474973', '#ED808C']
  },
  {
    key: 'somethun2',
    title: 'Title 2',
    text: 'Reach out to your Vilijers for help and help them in return.',
    icon: 'ios-beer-outline',
    colors: ['#474973', '#ED808C']
  },
  {
    key: 'somethun3',
    title: 'Title 3',
    text: `We will take care of the rest - scheduling, reminders and urgent alerts.
    By continuing you agree to our Terms and Conditions`,
    icon: 'ios-beer-outline',
    colors: ['#474973', '#ED808C']
  }
];

export default class WelcomeScreen extends Component {
  _renderItem = props => (
    <LinearGradient
      style={[
        styles.mainContent,
        {
          paddingTop: props.topSpacer,
          paddingBottom: props.bottomSpacer
        }
      ]}
      colors={props.colors}
      start={{ x: 0, y: 0.1 }}
      end={{ x: 0.1, y: 1 }}
    >
      <Ionicons
        style={{ backgroundColor: 'transparent' }}
        name={props.icon}
        size={200}
        color="white"
      />
      <View>
        <Text style={styles.title}>{props.title}</Text>
        <Text style={styles.text}>{props.text}</Text>
      </View>
    </LinearGradient>
  );

  render() {
    _onDone = () => {
      // User finished the introduction. Show "real" app
      //this.props.navigation.navigate('Login');
      this.props.navigation.dispatch(navigateAction);
      //this.props.rootNavigation.navigation.navigate('Login');
    };
    return (
      <AppIntroSlider
        slides={slides}
        renderItem={this._renderItem}
        bottomButton
        onDone={this._onDone}
      />
    );
  }
}

Thank you for your help!

**Comment by urvitrivedi** [comment]
I am also adding my navigation section. 
**MainNavigator.js**

import React from 'react';
import { Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { TabNavigator, TabBarBottom } from 'react-navigation';

import Colors from '../constants/Colors';

import HomeScreen from '../screens/HomeScreen';
import VillagerScreen from '../screens/VillagerScreen';
import DiscoverScreen from '../screens/DiscoverScreen';
import CalendarScreen from '../screens/CalendarScreen';
import ChatScreen from '../screens/ChatScreen';

export default TabNavigator(
  {
    Home: {
      screen: HomeScreen
    },
    Vilijers: {
      screen: VillagerScreen
    },
    Discover: {
      screen: DiscoverScreen
    },
    Calendar: {
      screen: CalendarScreen
    },
    Chat: {
      screen: ChatScreen
    }
  },
  {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused }) => {
        const { routeName } = navigation.state;
        let iconName;
        switch (routeName) {
          case 'Home':
            iconName =
              Platform.OS === 'ios'
                ? `ios-home${focused ? '' : '-outline'}`
                : 'md-home';
            break;
          case 'Vilijers':
            iconName =
              Platform.OS === 'ios'
                ? `ios-people${focused ? '' : '-outline'}`
                : 'md-people';
            break;
          case 'Discover':
            iconName =
              Platform.OS === 'ios'
                ? `ios-search${focused ? '' : '-outline'}`
                : 'md-search';
            break;
          case 'Calendar':
            iconName =
              Platform.OS === 'ios'
                ? `ios-calendar${focused ? '' : '-outline'}`
                : 'md-calendar';
            break;
          case 'Chat':
            iconName =
              Platform.OS === 'ios'
                ? `ios-chatbubbles${focused ? '' : '-outline'}`
                : 'md-chatbubbles';
        }
        return (
          <Ionicons
            name={iconName}
            size={28}
            style={{ marginBottom: -3 }}
            color={focused ? Colors.tabIconSelected : Colors.tabIconDefault}
          />
        );
      }
    }),
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    animationEnabled: false,
    swipeEnabled: false
  }
);

**RootNavigation.js**

import { Notifications } from 'expo';
import React from 'react';
import { StackNavigator, NavigationActions } from 'react-navigation';

import MainTabNavigator from './MainTabNavigator';
import registerForPushNotificationsAsync from '../api/registerForPushNotificationsAsync';

import WelcomeScreen from '../screens/WelcomeScreen';
import LoginScreen from '../screens/LoginScreen';

const RootStackNavigator = StackNavigator(
  {
    Welcome: {
       screen: WelcomeScreen,
       navigationOptions: ({ navigation }) => ({
         header: null
    })
     },
     Login: {
        screen: LoginScreen,
       navigationOptions: ({ navigation }) => ({
       header: null
    })
    },
    Main: {
      screen: MainTabNavigator
    }
  },
  {
    navigationOptions: () => ({
      headerTitleStyle: {
        fontWeight: 'normal'
      }
    })
  }
);

const navigateAction = NavigationActions.navigate({
  routeName: 'Welcome',

  params: {},

  action: NavigationActions.navigate({ routeName: 'Login' })
});

export default class RootNavigator extends React.Component {
  componentDidMount() {
    this._notificationSubscription = this._registerForPushNotifications();
  }

  componentWillUnmount() {
    this._notificationSubscription && this._notificationSubscription.remove();
  }

  render() {
    return <RootStackNavigator />;
  }

  _registerForPushNotifications() {
    // Send our push token over to our backend so we can receive notifications
    // You can comment the following line out if you want to stop receiving
    // a notification every time you open the app. Check out the source
    // for this function in api/registerForPushNotificationsAsync.js
    registerForPushNotificationsAsync();

    // Watch for incoming notifications
    this._notificationSubscription = Notifications.addListener(
      this._handleNotification
    );
  }

  _handleNotification = ({ origin, data }) => {
    console.log(
      `Push notification ${origin} with data: ${JSON.stringify(data)}`
    );
  };
}

**Comment by urvitrivedi** [comment]
Hi Jacse,
Just checking in, if you had any luck?

**Comment by Jacse** [comment]
@urvitrivedi there are a number of errors in your code. I suggest you try without the navigator and see if you can get the `onDone`-function to fire properly first - you can then add more functionality as you go.

In the future when you paste JS into GitHub make sure you fix the indentation and start it with \`\`\`js and end it with \`\`\` like so:

\`\`\`js
const jsCode = 'now renders nicely';
\`\`\`

That way it will be much easier to read 😄 :
```js
const jsCode = 'now renders nicely';
```

**Comment by urvitrivedi** [comment]
Unfortunately, I have to use the navigator.
