### ISSUE TITLE
Cant reduce height with custom styles

### ISSUE THREAD

**Issue by Billmike** [Jacse/react-native-app-intro-slider#77]
I'm trying to achieve something like this (see attached image) using your component, but I can't seem to reduce the height the custom gradient takes up? Is it possible to achieve something like this using your package? Seems it's not so easily customizable

<img width="402" alt="screenshot 2018-11-20 at 10 50 40 am" src="https://user-images.githubusercontent.com/24798364/48765401-5ccbe400-ecb2-11e8-8e01-dade6daab8a8.png">

**Comment by Jacse** [comment]
You can supply your own function to render items just as you see fit - including making them smaller. It is not yet, however, possible to show the next slide "peeking" in.
