### ISSUE TITLE
Wrong offset when width of slide is not equal Dimensions.get('window')

### ISSUE THREAD

**Issue by codyng** [Jacse/react-native-app-intro-slider#79]
When the slider is wrapped within a <View /> with some horizontal padding (20pt), and I set the width of the slide to be Dimensions.get('window').width - 40, the goToSlide() is wrong in the scrolling offset. Did you assume the initial width to be Dimensions.get('window')?

**Comment by codyng** [comment]
I just find the solution by overriding the onLayout method:

<AppIntroSlider
...
onLayout={() => {
    this.slider.setState({width: Dimensions.get('window').width - 40})
}}
...
/>

**Comment by Jacse** [comment]
Yeah, this is because the component assumes that it is taking up the full size of the screen. I'm glad you figured out a way to solve it.
