### ISSUE TITLE
skip click not working?

### ISSUE THREAD

**Issue by bamaarintoko** [Jacse/react-native-app-intro-slider#86]

**Comment by Jacse** [comment]
Could you be more specific? When you push the skip button the `onSkip`-function should be invoked.

**Comment by bamaarintoko** [comment]
but not in my project, when i push skip button, nothing happen

**Comment by bamaarintoko** [comment]
![skip](https://user-images.githubusercontent.com/28489752/50571268-4b5d1800-0dd8-11e9-9861-9f7a9bb9c47f.PNG)

**Comment by Schabaani** [comment]
same issue.

**Comment by TheAlgo** [comment]
same issue faced by me as well

**Comment by TheAlgo** [comment]
@bamaarintoko was your issue resolved?

**Comment by kkesley** [comment]
I have this issue as well. When I click skip, the slides are not going to the last one (basically nothing happened). but when I try using `onSkip` property, I can confirm the function is called when the button is pressed. But how to skip to the last page?

**Comment by krisnailafat** [comment]
my default skip doesnt work, help

**Comment by Jacse** [comment]
Could you please try with the newest version?
