### ISSUE TITLE
Bottom Button height is fixed

### ISSUE THREAD

**Issue by johnny-vikrant** [Jacse/react-native-app-intro-slider#88]
I'm using `bottonBotton` prop to render Next and Done button on the bottom. But after doing this I'm not able to increase the button padding. It seems the button height is fixed in AppIntroSlider.js

```
 bottomButtonContainer: {
    height: 44,
    marginHorizontal: 16,
  },
```

Here is my code:
```
<AppIntroSlider
  slides={slides}
  renderItem={this.renderItem} 
  renderDoneButton={this.renderDoneButton}
  renderNextButton={this.renderNextButton}
  bottomButton
  onDone={this.handleNavigateNext}
/>
```

is there any way I can modify the bottomButton height?

**Comment by Jacse** [comment]
Fixed in master
