### ISSUE TITLE
Image scaling not accurate for android , but works for ios

### ISSUE THREAD

**Issue by fithaN** [Jacse/react-native-app-intro-slider#9]
Hi 
The image scaling was not same for android and ios.It scaled differently for android cropping some part of the image on the screen.
But it fits the image in ios.

![image](https://user-images.githubusercontent.com/33620488/34323546-4d6a4fd4-e8a2-11e7-8d33-22782345eea3.png)
![image](https://user-images.githubusercontent.com/33620488/34323548-5cc631dc-e8a2-11e7-9c0a-32bef55469ed.png)

**Comment by Jacse** [comment]
I'm suspecting this is an error with the way you have configured the slider. You could do full-screen background images by writing your own `renderItem`-method as such:

```js

const slides = [
  {
    key: 'a',
    image: require('./assets/1.jpg'),
  },
  {
    key: 'b',
    image: require('./assets/2.jpg'),
  },
  {
    key: 'somethun1',
    image: require('./assets/3.jpg'),
  }
];


export default class App extends React.Component {
  _renderItem = props => (
    <Image style={{ flex: 1, width: null, height: null, resizeMode: 'cover'}} source={props.image} />
  );
  render() {
    return (
      <AppIntroSlider
        slides={slides}
        renderItem={this._renderItem}
      />
    );
  }
}
```

You can see for yourself by running the example and replacing the code with that.

**Comment by raduflp** [comment]
I was facing a similar issue and I thought that maybe exposing the Image resizeMode prop as a configuration option would be useful. 
@Jacse what do you think?

**Comment by dashracer** [comment]
I have the same problem too. For now I directly change the resizeMode prop type from default slide to contain

**Comment by Jacse** [comment]
The component was primarily designed around having a title and a text on each slide. I see now that it is also used to display full-screen images without text (or do you simply want a full screen background while still having text?). Doing so should be pretty straightforward. Do you mind sharing your code, @dashracer and/or @raduflp? Did you try using my code?

@raduflp the image resizeMode can be set through imageStyle

**Comment by raduflp** [comment]
@Jacse I proposed to expose `resizeMode` as a separate configuration option because I wasn't able to set it through AppIntroSlider imageStyle as `resizeMode` is an Image prop separate from `style`.  Or am I missing something?

For the time being I changed your code in DefaultSlide.js:21 by adding the resizeMode manually like this: `        <Image source={this.props.image} style={this.props.imageStyle} resizeMode="contain" />`
but that's not production friendly. 

In my scenario, I have both title and text, but the images have different resolutions and aspect ratios, so setting the resizeMode to 'contain' fixes image layout issues. 

Great work btw :)

**Comment by Jacse** [comment]
I see, thanks for the write-up, @raduflp. If I'm not misreading the [documentation](https://facebook.github.io/react-native/docs/image.html#style) you can set `resizeMode` both as an explicit prop and through styles. Does setting the `resizeMode` through styles solve your issue?

**Comment by raduflp** [comment]
@Jacse you are right, `imageStyle` covers my scenario. I was using it improperly.  Thanks

**Comment by dashracer** [comment]
It work if we use custom render item function.
But it would be better if the default image can receive resizeMode props.

**Comment by Jacse** [comment]
I'm closing this @fithaN. If you still have problems let me know.

**Comment by deifos** [comment]
any tips for having full screen image per slide?
