### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by dacevedo12** [Jacse/react-native-app-intro-slider#96]
There's some of us that love TS and also find this lib extremely useful.  I will look into this  in a few weeks to make the contribution myself if you guys support the idea.

**Comment by mtakac** [comment]
@Jacse Are you open to have type declaration file as a part of the repo? I am using this lib quite often and I'd be happy to help out if you're open to the idea.

@dacevedo12 Have you made any progress on this?

**Comment by dacevedo12** [comment]
@mtakac I haven't used all the features of this library yet but here's is what I have so far:

```
declare module "react-native-app-intro-slider" {
    export interface Slide {
        colors: string[];
        icon: JSX.Element;
        key: string;
        text: string;
        title: string;
    }

    export interface SliderItemProps extends Slide {
        bottomSpacer: number;
        topSpacer: number;
        width: number;
    }

    export interface AppIntroSliderProps {
        nextLabel: string;
        doneLabel: string;
        slides: Slide[];
        renderItem: ((props: SliderItemProps) => JSX.Element);
        onDone: (() => void);
    }

    export default class AppIntroSlider extends React.Component<AppIntroSliderProps> { };
}
```

**Comment by Fallup** [comment]
@Jacse Thank you for the rewrite, but the `index.d.ts` is not exported, so we can't really use the types.

**Comment by Jacse** [comment]
> @Jacse Thank you for the rewrite, but the `index.d.ts` is not exported, so we can't really use the types.

You make a very good point!
