### ISSUE TITLE
Custom pagination style.

### ISSUE THREAD

**Issue by subramGrg** [Jacse/react-native-app-intro-slider#97]
At the moment pagination style is hardcoded (`paginationContainer`).

it would be nice to pass down custom pagination style. 

cause id like to place the pagination to the top instead of bottom.

**Comment by daisymacharia** [comment]
I am also facing the same restriction with the pagination styles

**Comment by Jacse** [comment]
I was thinking about rewriting the thing a little. What exactly were you hoping to achieve?

**Comment by daisymacharia** [comment]
<img width="243" alt="screenshot 2019-03-02 at 09 14 00" src="https://user-images.githubusercontent.com/28440972/53678107-8c37b700-3ccb-11e9-886c-aa410eba5636.png">

I was hoping to style my prev and next buttons like this but they seem to have a default style of `left: 0` and `right:0`, setting the `left`attribute on the prev button  pushes it to right side but the `onPress` remains on the original buttons position.

**Comment by Jacse** [comment]
Since that layout is quite far off the default I think you should consider setting `hidePagination` to true and simply create your own buttons completely. You can use `goToSlide()` to change the active slide on press.

**Comment by Jacse** [comment]
The `paginationStyle`-prop has just been introduced.

**Comment by subramGrg** [comment]
thanks @Jacse

**Comment by anniewey** [comment]
@Jacse can't find `paginationStyle` in v4.0.4. how to align the pagination to top?
