### ISSUE TITLE
Not working with react-native-18n

### ISSUE THREAD

**Issue by MayeuldP** [Jacse/react-native-app-intro-slider#98]
Hello.
I tried to use app-intro-slider with this library *React-Native-I18n*, 
but it appears that this setup didn't work : 
```
 const slides = [
     {
       key: 'somethun',
       title: 'Title 1',
       text: I18n.t("somethingtotranslate"),
       image: Images.logo_tutorial,
       backgroundColor: Colors.primary,
     }
]
```

My I18n librairie works well since the translation for others sentences in my app works like a charm... So I'm not able to say why it's not working with app-intro, didn't find anything... 
Any ideas ? 
Thanks for the help !

**Comment by Jacse** [comment]
That seems weird. What error message do you get?

**Comment by MayeuldP** [comment]
`[missing "fr-US.myWord" translation]` but as I wrote it above, the translation works well for my others separate basic screens...

**Comment by Jacse** [comment]
I sounds like it's an issue with the translation. Have you tried doing `console.log(I18n.t("somethingtotranslate")` does it print the piece of text that you were hoping for?

**Comment by MayeuldP** [comment]
Alright, I managed to resolve the issue. In fact, I declared my `const slides : []` outside the main `Class` : 

#### translation didn't work : 
```
const slides = [...]

class MyClass extends React.Component {
      render(){
             return(
                  <AppSlider ..../>);
     }
}
```

And doing something like that fixed it 
#### translation did work : 
```
class MyClass extends React.Component {
      render(){
             const slides = [...]
             
                return(
                  <AppSlider ..../>);
     }
}
```

Probably normal, but I thought it would've work in the first case... Anyway ! Working now :)
